export const MESSAGES_CHATBOT_OBJ_TYPE = {
    AREA_OF_LAW_LIST: 'AREA_OF_LAW_LIST',
    SUP_CAT_LIST: 'SUP_CAT_LIST',
    CAT_LIST: 'CAT_LIST',
    IS_GEOLOCATION: 'IS_GEOLOCATION',
    CONSUMERLOCATION: 'CONSUMERLOCATION'
};

export const MESSAGES_CHATCLIENT_OBJ_TYPE = {
    AREA_OF_LAW_IDS: 'AREA_OF_LAW_IDS',
    SUP_CAT_IDS: 'SUP_CAT_IDS',
    CHOSEN_CAT: 'CHOSEN_CAT',
    IS_GEOLOCATION_YES: 'IS_GEOLOCATION_YES',
    IS_GEOLOCATION_NO: 'IS_GEOLOCATION_NO',
    CONSUMERLOCATION_AUTOCOMPLETE: 'CONSUMERLOCATION_AUTOCOMPLETE'
};